### ISSUE TITLE
请教下如何在RecyclerView跳转ViewPager2的场景下使用~

### ISSUE THREAD

**Issue by yptang97** [Arcns/fast-transition#3]
如何在Activity_A的列表中点击item跳转Activity_B页面，B页面是Viewpager2可滑动切换item的场景下使用~，B页面切换item后返回A页面也能找到对应的item

**Comment by yptang97** [comment]
![PDXUXEW64@P`$JOU(DJ6P5D](https://user-images.githubusercontent.com/77526669/233884452-f7f19564-801f-45a4-a0b8-b2336833c4fb.png)

**Comment by Arcns** [comment]
不好意思，工作比较忙，最近才有空来更新/(ㄒoㄒ)/~~，我在项目[sample](https://github.com/Arcns/fast-transition/tree/master/sample)新增了结合ViewPager使用的场景，文档也新增了[补充，如何在跳转到新页面后，在返回时更改两边的共享元素](https://github.com/Arcns/fast-transition#3%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F)
